---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-buoyant
  namespace: linkerd-buoyant
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: linkerd-buoyant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd-buoyant
      version: "0.28"
  interval: 15m0s
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  values:
    licenseSecret: vss-linkerd-license
