---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  values:
    nodeSelector: {}
    tolerations: []
    cainjector:
      nodeSelector: {}
      tolerations: []
    webhook:
      nodeSelector: {}
      tolerations: []
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  values:
    nodeSelector: {}
    tolerations: []
