---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: "0.9.13"
  interval: 15m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
