---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-license
  namespace: linkerd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vss-linkerd-license
    creationPolicy: Owner
  data:
  - secretKey: license
    remoteRef:
      key: secret/data/linkerd
      property: license
